CREATE DATABASE IF NOT EXISTS smart_ocr CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE smart_ocr;

CREATE TABLE IF NOT EXISTS ocr_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  filepath VARCHAR(255) NOT NULL,
  extracted_text LONGTEXT NOT NULL,
  language VARCHAR(10) NOT NULL,
  font_type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
